### ISSUE TITLE
error in partitionReverseNotStable?

### ISSUE THREAD

**Issue by da0ka** [aldo-gutierrez/bitmasksorterJS#2]
main.js :line231
changed `range=1000` to `range=3*(1<<30)`
console report `Arrays Not Equal`

**Comment by aldo-gutierrez** [comment]
With range=3*(1<<29) it works, with 3*(1<<30) it fails. In theory It should work up to range = 0...(1<<30)*2-1

The RadixBitSorter algorithm is expecting a signed 32 bit signed integer, and the maximum positive 32bit integer is 2^31-1 

Also  JavaScript numbers are stored as double precision floating point number using IEEE 754 standard, that when performing
bitwise operations they return a temporary 32 bit integer where the bitwise operation is performed

https://www.w3schools.com/js/js_bitwise.asp

I need to update README.md to specify this limitations on the algorithm.


For future work I wanted to implement a int64 sorter, but as Javascript doesn't  support 64 bits Numbers I will have to use the new type BigInt with variable Integer Length.

Also it's possible to sort double floating point numbers with some modifications to the algorithm, so I also wanted to do that, but I will have to use Float64Array.

**Comment by da0ka** [comment]
line 151 changed `false` to `true` then result is correct. I tested with `range = 3*(1<<30)` and `range = -3*(1<<30)`

btw, `getMaskBit` return Array object. Why not `mask & inv_mask` ?
result is always `maskParts[0] & maskParts[1]`, so return should be number.
And what is line 171 and 179 means? maybe it is unnecessary.

**Comment by aldo-gutierrez** [comment]
Updated documentation to explain that the range that supports "sortInt" is -(2 ** 31) ... 2 ** 31 - 1  which is the same as  -2 * (1 << 30) ... 2 * (1 << 30) - 1.  As JavaScript works with signed 32 bit Integer numbers when using bit operators like [&] [|] [~]

I thought a lot about line 151, only conclusion was that setting unsigned to false make it to simulate a unsigned integer of 32 bits so the range was expanded from 0 ..  2**32 -1 and worked 3*(1<<30). However unsigned variable was removed in new version.

New function 'sortNumber' supports all the range of normal Numbers in Javascript that internally are Float64 values, so that will support any integer that can be represented in a Float64 value.

getMaskBit (renamed to calculateMaskInt) returned an array because in other implementations as in Java, I used in a parallel algorithm, however in the javascript version I won't use a parallel implementation so it will just return a number as suggested.

Line 171-179 is a typing error thanks
